options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTIONS_DIR: "functions"
  _ONLY: "functions"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
    env: FIREBASE_TOKEN

steps:
- name: "node:20"
  id: "Install"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm i
    npm run lint || true  
    npm run build --if-present

- name: "node:20"
  id: "Deploy"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  secretEnv: [ "FIREBASE_TOKEN" ]
  args:
  - -lc
  - |
    npx firebase-tools@latest deploy \
      --project ${PROJECT_ID} \
      --only ${_ONLY} \
      --non-interactive \
      --token "$$FIREBASE_TOKEN"
