options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTIONS_DIR: "functions"
  _ONLY: "functions"

steps:
- name: "node:20"
  id: "Install"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm i

- name: "node:20"
  id: "Lint"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm run lint || true

- name: "node:20"
  id: "Build"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm run build --if-present

- name: "us-docker.pkg.dev/firebase-cli/us/firebase"
  id: "Deploy"
  args:
  - |
    deploy 
    --project=${PROJECT_ID}
    --only=${_ONLY}
