options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTIONS_DIR: "functions"
  _ONLY: "functions"

steps:
- name: "node:20"
  id: "NPM Install"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm i

- name: "node:20"
  id: "Install Platform-Specific Dependencies"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm i --os=linux --libc=musl --cpu=x64 sharp

- name: "us-docker.pkg.dev/firebase-cli/us/firebase"
  id: "Deploy Functions"
  dir: "${_FUNCTIONS_DIR}"
  args: [ 'deploy', '${PROJECT_ID}', '--only=${_ONLY}' ]
