options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTIONS_DIR: "functions"
  _ONLY: "functions"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
    env: FIREBASE_TOKEN

steps:
- name: "node:20"
  id: "Install"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm i

- name: "node:20"
  id: "Lint"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm run lint || true

- name: "node:20"
  id: "Build"
  dir: "${_FUNCTIONS_DIR}"
  entrypoint: bash
  args:
  - -lc
  - |
    npm run build --if-present

- name: "us-docker.pkg.dev/firebase-cli/us/firebase"
  id: "Deploy"
  args:
  - -lc
  - |
    deploy ${PROJECT_ID}
    --only=${_ONLY}
